### ISSUE TITLE
Question about anchor shapes calculation

### ISSUE THREAD

**Issue by alex96295** [QiuJueqin/SqueezeDet-PyTorch#2]
Hi (always me),

when I have to calculate anchor seeds for a dataset, how does it deal with different input sizes? I mean, the numbers that the code gives me back are referred to which image height-width tuple if the input had different sizes?

Thank you!

**Comment by QiuJueqin** [comment]
Hi, I did not consider this situation when wrote the anchor calculator. 

In your case, multiplying the box's width and height [(here)](https://github.com/QiuJueqin/SqueezeDet-PyTorch/blob/b0d80daa0147c968d43f3c38bc416394419c4bcc/src/utils/compute_dataset_seed_anchors.py#L40) by the ratio of the network's input size (like [here](https://github.com/QiuJueqin/SqueezeDet-PyTorch/blob/b0d80daa0147c968d43f3c38bc416394419c4bcc/src/datasets/kitti.py#L15)) to the actual current image size may be a good solution.

**Comment by alex96295** [comment]
OK thank you!

**Comment by alex96295** [comment]
@QiuJueqin I closed this but I would have another question: I am really grateful for the patience, but who to ask to better than you --> you pass as input a dictionary, is it right? Would it be possible to have as input just the tensor image? 
I mean, if one wants to implement the network on hardware, would it be better to have a tensor (and stop) as input, or I am missing something? Moreover, passing the input as a tensor only has been what I have done in my - really little - experience with detection up to now

And where is in the code the point where you decide that the input is a dictionary?

Take your time to answer I know I am the annoying person here!

**Comment by QiuJueqin** [comment]
The input structure can be flexible in PyTorch: it only care about the node itself that the computation graph is tracking, but not the container where it is stored. I pass a dict as input to record some image meta like original size, file name, etc., but sure it's ok to directly pass a tensor as input to you model/module.

**Comment by alex96295** [comment]
Ok because in this way also at inference time I am required to pass a dictionary. In order to avoid that, would it be necessary to simply pass the input tensor - without image meta infos - to the network at training time?

**Comment by QiuJueqin** [comment]
It's ok, you can discard imega_meta and pass image and ground-truth as two individual tensors to the model at training time.

**Comment by alex96295** [comment]
Got it, thanks!
