### ISSUE TITLE
Question about kitti dataset

### ISSUE THREAD

**Issue by sparshgarg23** [QiuJueqin/SqueezeDet-PyTorch#8]
Hi,I am new to the computer vision field and I have some questions about the usage of kitti dataset.
I went to the cvlibs site,and it seems that for the 2d detection task,there are several files such as 
left images
right images
temporal information
point cloud
As such since this repo is focused on 2d detection,I am assuming the link in the download section is referring to the left images,apart from that do we also need to download the calibration matrices file.
Apart from this,is there any tutorial/blog that suggests which files to download in kitti depending on the task?

**Comment by QiuJueqin** [comment]
Hi, calibration matrices are not necessary. The only data required to run this repo are left images and 2D object labels. 

You can find more information about the data in [KITTI's web](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=2d), and some usage details may be found in the README files attached in the downloaded archives.

**Comment by sparshgarg23** [comment]
Hi,on running main.py demo,I am getting the error 
" No such file or directory: '/content/SqueezeDet-PyTorch/data/kitti/image_sets/val.txt'
I was able to solve this issue by generating the image-sets as mentioned in the readme,but now when I run demo.py on colab,I end up recieivng the error cannot connect to X server.Any thoughts on how to resolve this?

**Comment by QiuJueqin** [comment]
@sparshgarg23 I've encountered similar issue. Try to add

```
matplotlib.use('Agg')
```

to [line #9 in logger.py](https://github.com/QiuJueqin/SqueezeDet-PyTorch/blob/b0d80daa0147c968d43f3c38bc416394419c4bcc/src/utils/logger.py#L9).

**Comment by sparshgarg23** [comment]
Ok ,I will look into it,thanks
